quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_YFSQne3lZ2mp
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-crimson-credit-b4z908ly.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=truesssssss