quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=TU_USUARIO_NEON
quarkus.datasource.password=TU_PASSWORD_NEON
quarkus.datasource.jdbc.url=jdbc:postgresql://TU_HOST_NEON/neondb?sslmode=require

quarkus.hibernate-orm.database.generation=update